name: LinuxRelease
on:
  workflow_call:
    inputs:
      override_git_describe:
        type: string
      git_ref:
        type: string
      skip_tests:
        type: string
  workflow_dispatch:
    inputs:
      override_git_describe:
        type: string
        description: 'Override the git describe version'
      git_ref:
        type: string
        description: 'Git reference to checkout'
      skip_tests:
        type: string
        description: 'Tests to skip'

  repository_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!feature'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/LinuxRelease.yml'

  pull_request:
    types: [ opened, reopened, ready_for_review ]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/LinuxRelease.yml'

concurrency:
  group: linuxrelease-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  OVERRIDE_GIT_DESCRIBE: ${{ inputs.override_git_describe }}

jobs:
  linux-release-64:
    name: Linux (x64)
    runs-on: ubuntu-22.04
    env:
      EXTENSION_CONFIGS: '${GITHUB_WORKSPACE}/.github/config/bundled_extensions.cmake'
      ENABLE_EXTENSION_AUTOLOADING: 1
      ENABLE_EXTENSION_AUTOINSTALL: 1
      GEN: ninja
      BUILD_BENCHMARK: 1
      FORCE_WARN_UNUSED: 1
      DUCKDB_RUN_PARALLEL_CSV_TESTS: 1
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - uses: ./.github/actions/ubuntu_22_setup

      - name: Install pytest
        run: pip install pytest

      - name: Build
        shell: bash
        run: make

      - name: Print platform
        shell: bash
        run: ./build/release/duckdb -c "PRAGMA platform;"

      - name: Test
        shell: bash
        if: ${{ inputs.skip_tests != 'true' }}
        run: |
          make
          python scripts/run_tests_one_by_one.py build/release/test/unittest "*" --time_execution

      - name: Tools Tests
        shell: bash
        if: ${{ inputs.skip_tests != 'true' }}
        run: |
          python -m pytest tools/shell/tests --shell-binary build/release/duckdb
