name: LinuxRelease
on:
  workflow_call:
    inputs:
      override_git_describe:
        type: string
      git_ref:
        type: string
      skip_tests:
        type: string
  workflow_dispatch:
    inputs:
      override_git_describe:
        type: string
        description: 'Override the git describe version'
      git_ref:
        type: string
        description: 'Git reference to checkout'
      skip_tests:
        type: string
        description: 'Tests to skip'

  repository_dispatch:
#  push:
#    branches:
#      - '**'
#      - '!main'
#      - '!feature'
#    paths-ignore:
#      - '**.md'
#      - 'tools/**'
#      - '!tools/shell/**'
#      - '.github/patches/duckdb-wasm/**'
#      - '.github/workflows/**'
#      - '!.github/workflows/LinuxRelease.yml'

  pull_request:
    types: [ opened, reopened, ready_for_review ]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/LinuxRelease.yml'

concurrency:
  group: linuxrelease-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  OVERRIDE_GIT_DESCRIBE: ${{ inputs.override_git_describe }}

jobs:
  linux-release-64:
    name: Linux (x64)
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --user root
    env:
      EXTENSION_CONFIGS: '${GITHUB_WORKSPACE}/.github/config/bundled_extensions.cmake'
      ENABLE_EXTENSION_AUTOLOADING: 1
      ENABLE_EXTENSION_AUTOINSTALL: 1
      GEN: ninja
      BUILD_BENCHMARK: 1
      FORCE_WARN_UNUSED: 1
      DUCKDB_RUN_PARALLEL_CSV_TESTS: 1
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      RUNNER_ALLOW_RUNASROOT: 1

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - uses: ./.github/actions/ubuntu_22_setup
        with:
          ccache: 0

      - name: Install pytest
        run: |
          python3 -m pip install pytest

      - name: Build
        shell: bash
        run: make

      - name: Print platform
        shell: bash
        run: ./build/release/duckdb -c "PRAGMA platform;"

      - name: Test
        shell: bash
        if: ${{ inputs.skip_tests != 'true' }}
        run: |
          make
          python3 scripts/run_tests_one_by_one.py build/release/test/unittest "*" --time_execution

      - name: Tools Tests
        shell: bash
        if: ${{ inputs.skip_tests != 'true' }}
        run: |
          python3 -m pytest tools/shell/tests --shell-binary build/release/duckdb


  # Linux extensions for builds that use C++11 ABI, currently these are all linux builds based on ubuntu >= 18 (e.g. NodeJS)
  # note that the linux-release-64 is based on the manylinux-based extensions, which are built in .github/workflows/Python.yml
  linux-extensions-64:
    # Builds extensions for linux_amd64
    name: Linux Extensions (x64)
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --user root
    needs: linux-release-64
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - uses: ./.github/actions/ubuntu_22_setup
        with:
          vcpkg: 1
          openssl: 1
          ccache: 1
          git_ref: ${{ inputs.git_ref }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure OpenSSL for Rust
        run: |
          echo "OPENSSL_ROOT_DIR=`pwd`/build/release/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_DIR=`pwd`/build/release/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=`pwd`/build/release/vcpkg_installed/x64-linux/include" >> $GITHUB_ENV
          echo "OPENSSL_USE_STATIC_LIBS=true" >> $GITHUB_ENV

      - uses: ./.github/actions/build_extensions
        with:
          vcpkg_target_triplet: x64-linux
          post_install: rm build/release/src/libduckdb*
          deploy_as: linux_amd64
          treat_warn_as_error: 0
          run_tests: ${{ inputs.skip_tests != 'true' && 1 || 0 }}
          run_autoload_tests: ${{ inputs.skip_tests != 'true' && 1 || 0 }}
          s3_id: ${{ secrets.S3_ID }}
          s3_key: ${{ secrets.S3_KEY }}
          signing_pk: ${{ secrets.DUCKDB_EXTENSION_SIGNING_PK }}
          ninja: 1

      - uses: actions/upload-artifact@v3
        with:
          name: linux-extensions-64
          path: |
            build/release/extension/*/*.duckdb_extension

  symbol-leakage:
    name: Symbol Leakage
    needs: linux-release-64
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --user root

    if: ${{ inputs.skip_tests != 'true' }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@v1.2.11
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

      - name: Build
        shell: bash
        run: make

      - name: Symbol Leakage Test
        shell: bash
        run: python3 scripts/exported_symbols_check.py build/release/src/libduckdb*.so

  amalgamation-tests:
    name: Amalgamation Tests
    needs: linux-release-64
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --user root
    env:
      CC: clang
      CXX: clang++
    if: ${{ inputs.skip_tests != 'true' }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"

      - name: Generate Amalgamation
        shell: bash
        run: |
          python scripts/amalgamation.py --extended
          clang++ -std=c++17 -Isrc/amalgamation src/amalgamation/duckdb.cpp -emit-llvm -S -O0
